/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package info5100.petinsurance.ui.insurance;

import info5100.petinsurance.model.UserAccount;
import info5100.petinsurance.model.insurance.InsuranceDetails;
import info5100.petinsurance.model.insurance.InsurancePlan;
import info5100.petinsurance.ui.WelcomeFrame;
import info5100.petinsurance.utilities.Constants;
import info5100.petinsurance.utilities.DatabaseConnection;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashit
 */
public class InsuranceAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InsuranceAdmin
     */
    String planNameSelected;
    UserAccount ua;
    Map<String, Integer> planLookup = new HashMap<>();

    public InsuranceAdmin(UserAccount ua) {
        this.ua = ua;
        planNameSelected = "";
        initComponents();
        anmlIDTextField1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        modifyPlanButton = new javax.swing.JButton();
        updateInsuranceButton = new javax.swing.JButton();
        createPlanButton = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createPlan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        planName = new javax.swing.JTextField();
        planCoverage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        premiumAmount = new javax.swing.JTextField();
        validity = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inclusionTextField = new javax.swing.JTextField();
        savePlanButton = new javax.swing.JButton();
        updateInsurancePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        existingConditions = new javax.swing.JComboBox<>();
        planUpdateInsurance = new javax.swing.JComboBox<>();
        anmlIDTextField1 = new javax.swing.JTextField();
        updateInsuranceDetailsButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        updateInsuranceDetailsTable = new javax.swing.JTable();
        modifyPlanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modifyPlanPanelTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        premiumAmountModify = new javax.swing.JTextField();
        inclusionModify = new javax.swing.JTextField();
        planCoverageModify = new javax.swing.JTextField();
        validityModify = new javax.swing.JComboBox<>();
        updatePlan = new javax.swing.JButton();
        updateSelectedPlan = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Insurance Admin");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        modifyPlanButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modifyPlanButton.setText(" Modify an Existing Plan");
        modifyPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPlanButtonActionPerformed(evt);
            }
        });

        updateInsuranceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateInsuranceButton.setText("Update Insurance Details ");
        updateInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsuranceButtonActionPerformed(evt);
            }
        });

        createPlanButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createPlanButton.setText("Add a New Plan");
        createPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyPlanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateInsuranceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(createPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(modifyPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(updateInsuranceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/petinsurance/Images/pet_insurance.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
            .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentPanel.add(homePanel, "card5");

        createPlan.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Premium Amount");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Validity(In Months)");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Plan Coverage Amount");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Plan Name");

        validity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Inclusion");

        savePlanButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savePlanButton.setText("Save");
        savePlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePlanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createPlanLayout = new javax.swing.GroupLayout(createPlan);
        createPlan.setLayout(createPlanLayout);
        createPlanLayout.setHorizontalGroup(
            createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlanLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPlanLayout.createSequentialGroup()
                        .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createPlanLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inclusionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(planCoverage)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPlanLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(premiumAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(planName, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createPlanLayout.createSequentialGroup()
                        .addComponent(savePlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))))
        );
        createPlanLayout.setVerticalGroup(
            createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createPlanLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(premiumAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(validity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(inclusionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(createPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(savePlanButton)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        parentPanel.add(createPlan, "card5");

        updateInsurancePanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Animal ID");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Plan");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Existing Medical Conditions");

        existingConditions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        existingConditions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
        existingConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingConditionsActionPerformed(evt);
            }
        });

        planUpdateInsurance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        planUpdateInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planUpdateInsuranceActionPerformed(evt);
            }
        });

        updateInsuranceDetailsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateInsuranceDetailsButton.setText("Update");
        updateInsuranceDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsuranceDetailsButtonActionPerformed(evt);
            }
        });

        updateInsuranceDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal ID", "Plan Name", "Start Date", "Existing Conditions"
            }
        ));
        updateInsuranceDetailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateInsuranceDetailsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(updateInsuranceDetailsTable);

        javax.swing.GroupLayout updateInsurancePanelLayout = new javax.swing.GroupLayout(updateInsurancePanel);
        updateInsurancePanel.setLayout(updateInsurancePanelLayout);
        updateInsurancePanelLayout.setHorizontalGroup(
            updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(updateInsurancePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(63, 63, 63)
                .addGroup(updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(anmlIDTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planUpdateInsurance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(existingConditions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(updateInsurancePanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(updateInsuranceDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        updateInsurancePanelLayout.setVerticalGroup(
            updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInsurancePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addGroup(updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anmlIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planUpdateInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(updateInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(existingConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(updateInsuranceDetailsButton)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        parentPanel.add(updateInsurancePanel, "card5");

        modifyPlanPanel.setBackground(new java.awt.Color(153, 204, 255));

        modifyPlanPanelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plan Name", "Premium Amount", "Validity", "Inclusions", "Coverage Amount"
            }
        ));
        jScrollPane1.setViewportView(modifyPlanPanelTable);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Premium Amount");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Validity(In Months)");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Inclusion");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Plan Coverage Amount");

        validityModify.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        updatePlan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updatePlan.setText("Save");
        updatePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePlanActionPerformed(evt);
            }
        });

        updateSelectedPlan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateSelectedPlan.setText("Update Selected Plan");
        updateSelectedPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSelectedPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyPlanPanelLayout = new javax.swing.GroupLayout(modifyPlanPanel);
        modifyPlanPanel.setLayout(modifyPlanPanelLayout);
        modifyPlanPanelLayout.setHorizontalGroup(
            modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(planCoverageModify, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPlanPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inclusionModify, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyPlanPanelLayout.createSequentialGroup()
                                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(premiumAmountModify, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validityModify, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(updateSelectedPlan))
                    .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(updatePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        modifyPlanPanelLayout.setVerticalGroup(
            modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyPlanPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateSelectedPlan)
                .addGap(32, 32, 32)
                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(premiumAmountModify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(validityModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inclusionModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(modifyPlanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(planCoverageModify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(updatePlan)
                .addContainerGap())
        );

        parentPanel.add(modifyPlanPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlanButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(createPlan);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_createPlanButtonActionPerformed

    private void modifyPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPlanButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(modifyPlanPanel);
        parentPanel.repaint();
        parentPanel.revalidate();

        populateModifyPlanTable();

    }//GEN-LAST:event_modifyPlanButtonActionPerformed

    private void updateInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsuranceButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(updateInsurancePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        populateAllInsurancePlans();
        populateAllActiveInsurance();
    }//GEN-LAST:event_updateInsuranceButtonActionPerformed


    private void savePlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePlanButtonActionPerformed
        // TODO add your handling code here:
        InsurancePlan plan = new InsurancePlan(planName.getText(), inclusionTextField.getText(),
                Integer.valueOf(validity.getSelectedItem().toString()),
                Integer.valueOf(premiumAmount.getText()), Integer.valueOf(planCoverage.getText()));

        try {
            ResultSet rs = DatabaseConnection.getData("select * from InsurancePlan", false);
            if (!rs.next()) {
                DatabaseConnection.storeData(plan);
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Plan Created!");
            } else {

                rs = DatabaseConnection.getData("select * from InsurancePlan", false);
                boolean flag = true;
                while (rs.next()) {
                    if (rs.getString(2).equalsIgnoreCase(planName.getText())) {
                        JFrame jFrame = new JFrame();
                        JOptionPane.showMessageDialog(jFrame, "There's already a plan with same name, Please enter a new name!");
                        flag = false;

                    }
                }
                if (flag) {
                    DatabaseConnection.storeData(plan);
                    JFrame jFrame = new JFrame();
                    JOptionPane.showMessageDialog(jFrame, "Plan Created!");
                }
            }
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_savePlanButtonActionPerformed

    private void updatePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePlanActionPerformed
        // TODO add your handling code here:
        InsurancePlan plan = new InsurancePlan(planNameSelected,
                inclusionModify.getText(),
                Integer.valueOf(validityModify.getSelectedItem().toString()),
                Integer.valueOf(premiumAmountModify.getText()),
                Integer.valueOf(planCoverageModify.getText()));

        DatabaseConnection.updatePlan(plan);

        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame, planNameSelected + " Plan Updated!");
        populateModifyPlanTable();
    }//GEN-LAST:event_updatePlanActionPerformed

    private void updateSelectedPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSelectedPlanActionPerformed
        // TODO add your handling code here:
        int selectedRow = modifyPlanPanelTable.getSelectedRow();
        premiumAmountModify.setText(modifyPlanPanelTable.getValueAt(selectedRow, 1).toString());
        planCoverageModify.setText(modifyPlanPanelTable.getValueAt(selectedRow, 4).toString());
        inclusionModify.setText(modifyPlanPanelTable.getValueAt(selectedRow, 3).toString());
        validityModify.setSelectedItem(modifyPlanPanelTable.getValueAt(selectedRow, 2).toString());

        planNameSelected = modifyPlanPanelTable.getValueAt(selectedRow, 0).toString();

    }//GEN-LAST:event_updateSelectedPlanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new WelcomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void planUpdateInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planUpdateInsuranceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planUpdateInsuranceActionPerformed

    private void updateInsuranceDetailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateInsuranceDetailsTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = updateInsuranceDetailsTable.getSelectedRow();
        anmlIDTextField1.setText(updateInsuranceDetailsTable.getValueAt(selectedRow, 0).toString());
        planUpdateInsurance.setSelectedItem(updateInsuranceDetailsTable.getValueAt(selectedRow, 1).toString());
        existingConditions.setSelectedItem(updateInsuranceDetailsTable.getValueAt(selectedRow, 2).toString());

    }//GEN-LAST:event_updateInsuranceDetailsTableMouseClicked

    private void existingConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existingConditionsActionPerformed

    private void updateInsuranceDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsuranceDetailsButtonActionPerformed
        // TODO add your handling code here:
        try {
            ResultSet rs = DatabaseConnection.getData(Constants.GETINSURANCEFORPET + updateInsuranceDetailsTable.getValueAt(updateInsuranceDetailsTable.getSelectedRow(), 0).toString(), false);
            while(rs.next()){
                int insuranceID = rs.getInt("id");
                InsuranceDetails insurance = new InsuranceDetails(rs.getInt("animalID"),
                rs.getDate("dateOfInsurance"),
                        existingConditions.getSelectedItem().toString(),
                        planLookup.get(planUpdateInsurance.getSelectedItem().toString()), null      
                );
                insurance.setId(insuranceID);
                DatabaseConnection.updateInsuranceDetails(insurance);
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Insurance Details updated");
                populateAllActiveInsurance();
            }
        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_updateInsuranceDetailsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InsuranceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InsuranceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InsuranceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InsuranceAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InsuranceAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anmlIDTextField1;
    private javax.swing.JPanel createPlan;
    private javax.swing.JButton createPlanButton;
    private javax.swing.JComboBox<String> existingConditions;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextField inclusionModify;
    private javax.swing.JTextField inclusionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton modifyPlanButton;
    private javax.swing.JPanel modifyPlanPanel;
    private javax.swing.JTable modifyPlanPanelTable;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JTextField planCoverage;
    private javax.swing.JTextField planCoverageModify;
    private javax.swing.JTextField planName;
    private javax.swing.JComboBox<String> planUpdateInsurance;
    private javax.swing.JTextField premiumAmount;
    private javax.swing.JTextField premiumAmountModify;
    private javax.swing.JButton savePlanButton;
    private javax.swing.JButton updateInsuranceButton;
    private javax.swing.JButton updateInsuranceDetailsButton;
    private javax.swing.JTable updateInsuranceDetailsTable;
    private javax.swing.JPanel updateInsurancePanel;
    private javax.swing.JButton updatePlan;
    private javax.swing.JButton updateSelectedPlan;
    private javax.swing.JComboBox<String> validity;
    private javax.swing.JComboBox<String> validityModify;
    // End of variables declaration//GEN-END:variables
   private void populateModifyPlanTable() {
        DefaultTableModel model = (DefaultTableModel) modifyPlanPanelTable.getModel();
        model.setRowCount(0);
        try {

            ResultSet rs = DatabaseConnection.getData("select * from InsurancePlan", false);
            while (rs.next()) {
                Object[] row = {rs.getString("planName"), rs.getInt("planPremium"), rs.getInt("validity"), rs.getString("inclusions"), rs.getInt("planCoverage")};
                model.addRow(row);
            }
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    private void populateAllActiveInsurance() {
        DefaultTableModel model = (DefaultTableModel) updateInsuranceDetailsTable.getModel();
        model.setRowCount(0);
        try {

            ResultSet rs = DatabaseConnection.getData(Constants.GETALLACTIVEINSURANCE, false);
            while (rs.next()) {
                Object[] row = {rs.getInt("animalID"), rs.getString("planName"), rs.getDate("dateOfInsurance"), rs.getString("existingMedicalConditions")};
                model.addRow(row);
            }
        } catch (HeadlessException | SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    private void populateAllInsurancePlans() {
        String[] plans = new String[15];

        try {
            ResultSet plan = DatabaseConnection.getData("Select * from InsurancePlan", false);
            int i = 0;
            while (plan.next()) {
                plans[i] = plan.getString("planName");
                planLookup.put(plan.getString("planName"), plan.getInt("id"));
                i++;
            }
            plans = Arrays.stream(plans).filter(value -> value != null && value.length() > 0).toArray(size -> new String[size]);

        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }

        planUpdateInsurance.setModel(new javax.swing.DefaultComboBoxModel<>(plans));
    }

}
