/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package info5100.petinsurance.ui.petowner;

import info5100.petinsurance.model.UserAccount;
import info5100.petinsurance.model.animal.AnimalDetails;
import info5100.petinsurance.model.insurance.InsuranceClaim;
import info5100.petinsurance.model.insurance.InsuranceDetails;
import info5100.petinsurance.ui.SignUp;
import info5100.petinsurance.ui.WelcomeFrame;
import info5100.petinsurance.utilities.Constants;
import info5100.petinsurance.utilities.ValidationService;
import java.util.ArrayList;
import info5100.petinsurance.utilities.DatabaseConnection;
import info5100.petinsurance.utilities.WorkFlowStatus;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashit
 */
public class PetOwner extends javax.swing.JFrame {

    /**
     * Creates new form AnimalOwner
     */
    Map<String, Integer> hospitalLookup = new HashMap<>();
    Map<String, Integer> doctorLookup = new HashMap<>();
    Map<String, Integer> animalLookup = new HashMap<>();
    UserAccount ua;
    ResultSet plan;
    Map<String, Integer> planLookup = new HashMap<>();
    List<AnimalDetails> animals;
    private boolean flag;
     private boolean flag1;

    public PetOwner(UserAccount ua) {
        this.ua = ua;
        initComponents();
        animals = new ArrayList<>();

        populateInsurancePlans();
        populateAnimalsForSubmitClaim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        purchaseInsuranceButton2 = new javax.swing.JButton();
        cancelInsuranceButton = new javax.swing.JButton();
        submitclaimButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        parentPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        registerAnimalPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        breedTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        typeTextField = new javax.swing.JTextField();
        animalName = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        registerAnimalButton = new javax.swing.JButton();
        purchaseInsurancePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        existingMedicalConditions = new javax.swing.JComboBox<>();
        planComboBox = new javax.swing.JComboBox<>();
        animalIDTextField1 = new javax.swing.JTextField();
        purchaseButton = new javax.swing.JButton();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        purchaseInsuranceTable = new javax.swing.JTable();
        cancelInsurancePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        anmlIDCancelTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cancelInsurancePanelButton = new javax.swing.JButton();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        cancelInsuranceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        insuranceID = new javax.swing.JTextField();
        submitClaimPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        submitClaimTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        claimAmount = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        contactNumber = new javax.swing.JTextField();
        submitClaimButton = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        contactEmail = new javax.swing.JTextField();
        hospitalName = new javax.swing.JComboBox<>();
        doctorName = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        animalDropDown = new javax.swing.JComboBox<>();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerButton.setText("Register Animal");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        purchaseInsuranceButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        purchaseInsuranceButton2.setText("Purchase Insurance");
        purchaseInsuranceButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseInsuranceButton2ActionPerformed(evt);
            }
        });

        cancelInsuranceButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelInsuranceButton.setText("Cancel Insurance");
        cancelInsuranceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInsuranceButtonActionPerformed(evt);
            }
        });

        submitclaimButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submitclaimButton.setText("Submit Claim");
        submitclaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitclaimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submitclaimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(registerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchaseInsuranceButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelInsuranceButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(registerButton)
                .addGap(48, 48, 48)
                .addComponent(purchaseInsuranceButton2)
                .addGap(42, 42, 42)
                .addComponent(cancelInsuranceButton)
                .addGap(41, 41, 41)
                .addComponent(submitclaimButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel9.setBackground(new java.awt.Color(51, 153, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Pet Owner");

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
        );

        parentPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info5100/petinsurance/Images/registeruser.png"))); // NOI18N

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        parentPanel.add(homePanel, "card6");

        registerAnimalPanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Breed(optional)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Gender");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Animal Type");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Animal Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Age");

        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyTyped(evt);
            }
        });

        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        maleRadioButton.setText("Male");

        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        femaleRadioButton.setText("Female");

        registerAnimalButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerAnimalButton.setText("Register");
        registerAnimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerAnimalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerAnimalPanelLayout = new javax.swing.GroupLayout(registerAnimalPanel);
        registerAnimalPanel.setLayout(registerAnimalPanelLayout);
        registerAnimalPanelLayout.setHorizontalGroup(
            registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerAnimalPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerAnimalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerAnimalPanelLayout.createSequentialGroup()
                        .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(45, 45, 45)
                        .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerAnimalPanelLayout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(62, 62, 62)
                                .addComponent(femaleRadioButton))
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(animalName, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerAnimalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        registerAnimalPanelLayout.setVerticalGroup(
            registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerAnimalPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(femaleRadioButton)
                    .addComponent(maleRadioButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(registerAnimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(animalName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(registerAnimalButton)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        parentPanel.add(registerAnimalPanel, "card5");

        purchaseInsurancePanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Animal ID");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Start Date");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Plan");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Existing Medical Conditions");

        existingMedicalConditions.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        existingMedicalConditions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));

        planComboBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        planComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planComboBoxActionPerformed(evt);
            }
        });

        purchaseButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        purchaseButton.setText("Purchase");
        purchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseButtonActionPerformed(evt);
            }
        });

        purchaseInsuranceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal Name", "Type", "Breed", "Gender"
            }
        ));
        purchaseInsuranceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseInsuranceTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(purchaseInsuranceTable);

        javax.swing.GroupLayout purchaseInsurancePanelLayout = new javax.swing.GroupLayout(purchaseInsurancePanel);
        purchaseInsurancePanel.setLayout(purchaseInsurancePanelLayout);
        purchaseInsurancePanelLayout.setHorizontalGroup(
            purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(planComboBox, 0, 161, Short.MAX_VALUE)
                            .addComponent(existingMedicalConditions, 0, 161, Short.MAX_VALUE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(animalIDTextField1))
                        .addGap(0, 216, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(purchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        purchaseInsurancePanelLayout.setVerticalGroup(
            purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purchaseInsurancePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(animalIDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(purchaseInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(existingMedicalConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(purchaseButton)
                .addContainerGap())
        );

        parentPanel.add(purchaseInsurancePanel, "card4");

        cancelInsurancePanel.setBackground(new java.awt.Color(153, 204, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Animal Name");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("End Date");

        cancelInsurancePanelButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancelInsurancePanelButton.setText("Cancel Insurance");
        cancelInsurancePanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelInsurancePanelButtonActionPerformed(evt);
            }
        });

        cancelInsuranceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "InsuranceID", "Animal Name", "Plan", "Start Date"
            }
        ));
        cancelInsuranceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelInsuranceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(cancelInsuranceTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Insurance ID");

        insuranceID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                insuranceIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout cancelInsurancePanelLayout = new javax.swing.GroupLayout(cancelInsurancePanel);
        cancelInsurancePanel.setLayout(cancelInsurancePanelLayout);
        cancelInsurancePanelLayout.setHorizontalGroup(
            cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelInsurancePanelLayout.createSequentialGroup()
                .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cancelInsurancePanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(anmlIDCancelTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(insuranceID)
                            .addComponent(endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(cancelInsurancePanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(cancelInsurancePanelLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(cancelInsurancePanelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cancelInsurancePanelLayout.setVerticalGroup(
            cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cancelInsurancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anmlIDCancelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(cancelInsurancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(cancelInsurancePanelButton)
                .addGap(31, 31, 31))
        );

        parentPanel.add(cancelInsurancePanel, "card3");

        submitClaimPanel.setBackground(new java.awt.Color(153, 204, 255));

        submitClaimTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Animal ID", "Name", "Insurance ID", "Insurance Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        submitClaimTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitClaimTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(submitClaimTable);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Hospital Name");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Doc Contact Number");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Claim Amount");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Doctor Name");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Contact Number");

        claimAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claimAmountActionPerformed(evt);
            }
        });
        claimAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claimAmountKeyTyped(evt);
            }
        });

        contactNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactNumberKeyTyped(evt);
            }
        });

        submitClaimButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submitClaimButton.setText("Submit");
        submitClaimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitClaimButtonActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel25.setText("Email");

        jLabel26.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel26.setText("Animal");

        javax.swing.GroupLayout submitClaimPanelLayout = new javax.swing.GroupLayout(submitClaimPanel);
        submitClaimPanel.setLayout(submitClaimPanelLayout);
        submitClaimPanelLayout.setHorizontalGroup(
            submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addGroup(submitClaimPanelLayout.createSequentialGroup()
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(submitClaimPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(35, 35, 35)
                        .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(claimAmount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(contactNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(contactEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospitalName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(doctorName, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(animalDropDown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(submitClaimPanelLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(submitClaimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        submitClaimPanelLayout.setVerticalGroup(
            submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitClaimPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(animalDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claimAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(submitClaimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(contactEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(submitClaimButton)
                .addContainerGap())
        );

        parentPanel.add(submitClaimPanel, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(registerAnimalPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void purchaseInsuranceButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseInsuranceButton2ActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(purchaseInsurancePanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        populateAnimalstable();
    }//GEN-LAST:event_purchaseInsuranceButton2ActionPerformed

    private void cancelInsuranceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInsuranceButtonActionPerformed
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(cancelInsurancePanel);
        parentPanel.repaint();
        parentPanel.revalidate();

        populateCancelInsuranceTable();
    }//GEN-LAST:event_cancelInsuranceButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        new WelcomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void registerAnimalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerAnimalButtonActionPerformed
        // TODO add your handling code here:
        JFrame jFrame = new JFrame();
        if (animalName.getText().trim().isEmpty() && typeTextField.getText().trim().isEmpty() &&
               ageTextField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(jFrame, "All fields are empty. Please try again!");
        } else if (animalName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(jFrame, "Animal name field is empty. Please try again!");
        } else if (typeTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(jFrame, "Type field is empty!. Please try again!");
        } else if (ageTextField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(jFrame, "Age field is empty. Please try again!");
        } else if (!maleRadioButton.isSelected() && !femaleRadioButton.isSelected()) {
            JOptionPane.showMessageDialog(jFrame, "No gender selected. Please try again!");
        } else {
            String gender = maleRadioButton.isSelected() ? "male" : "female";
            AnimalDetails animal = new AnimalDetails(animalName.getText(), typeTextField.getText(), breedTextField.getText(),
                    Integer.valueOf(ageTextField.getText()),
                    gender, ua.getPersonID(), null);

            ResultSet rs = DatabaseConnection.storeData(animal);
            flag = true;
            ValidationService vs = new ValidationService();
            flag = vs.validateAge(ageTextField.getText());

            if (rs == null) {
                
                JOptionPane.showMessageDialog(jFrame, "Sorry the registration couldn't be completed. Please try again!");
            } else if (!flag) {
                JOptionPane.showMessageDialog(jFrame, "Age entered is wrong, please enter correct age!");
            } else {
                try {
                    while (rs.next()) {
                        String pronoun = gender.equals("male") ? "him" : "her";
                        JOptionPane.showMessageDialog(jFrame, "Your pet is Registered. We wish " + pronoun + " a good health");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(PetOwner.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_registerAnimalButtonActionPerformed

    private void purchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseButtonActionPerformed
        // TODO add your handling code here:
        boolean activeInsuranceExists = false;
        int animalId = 0;
        try {
            animalId = animals.stream().filter(a -> a.getAnimalName().equals(animalIDTextField1.getText())).collect(Collectors.toList()).get(0).getId();
            String select = Constants.GETINSURANCEFORPET + animalId;
            ResultSet rs = DatabaseConnection.getData(select, false);

            while (rs.next()) {
                activeInsuranceExists = true;
            }
        } catch (SQLException e) {
            Logger.getLogger(PetOwner.class.getName()).log(Level.SEVERE, null, e);

        }

        if (activeInsuranceExists) {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "There's 1 insurance already active. New purchase is prohibited");

        } else {
            InsuranceDetails insurance = new InsuranceDetails(animalId,
                    startDateChooser.getDate(), existingMedicalConditions.getSelectedItem().toString(),
                    planLookup.get(planComboBox.getSelectedItem().toString()), null);

            ResultSet rs = DatabaseConnection.storeData(insurance);

            if (null == rs) {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "failed to purchase insurance. Please try again");
            } else {
                JFrame jFrame = new JFrame();
                JOptionPane.showMessageDialog(jFrame, "Insurance purchased for with Start Date as :" + startDateChooser.getDate());
            }
        }

    }//GEN-LAST:event_purchaseButtonActionPerformed

    private void ageTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if (!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_ageTextFieldKeyTyped

    private void claimAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claimAmountKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if (!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_claimAmountKeyTyped

    private void claimAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claimAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claimAmountActionPerformed

    private void purchaseInsuranceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseInsuranceTableMouseClicked
        // TODO add your handling code here:
        animalIDTextField1.setText(purchaseInsuranceTable.getValueAt(purchaseInsuranceTable.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_purchaseInsuranceTableMouseClicked

    private void cancelInsurancePanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelInsurancePanelButtonActionPerformed
        // TODO add your handling code here:

        boolean activeInsuranceExists = false;
        InsuranceDetails activeInsuranceDetails = null;
        try {
            String select = Constants.GETINSURANCEFORPET + animalLookup.get(anmlIDCancelTextField.getText());
            ResultSet rs = DatabaseConnection.getData(select, false);

            while (rs.next()) {
                activeInsuranceExists = true;
                activeInsuranceDetails = new InsuranceDetails(
                        rs.getInt("animalID"), new Date(rs.getDate("dateOfInsurance").getDate()), rs.getString("existingmedicalconditions"), rs.getInt("planId"),
                        endDateChooser.getDate());
                activeInsuranceDetails.setId(rs.getInt("id"));
            }
        } catch (SQLException e) {
            Logger.getLogger(PetOwner.class.getName()).log(Level.SEVERE, null, e);

        }

        if (activeInsuranceExists) {
            DatabaseConnection.cancelInsurance(activeInsuranceDetails);
        } else {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "There's no active insurance.");

        }

    }//GEN-LAST:event_cancelInsurancePanelButtonActionPerformed

    private void cancelInsuranceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelInsuranceTableMouseClicked
        // TODO add your handling code here:
        anmlIDCancelTextField.setText(cancelInsuranceTable.getValueAt(cancelInsuranceTable.getSelectedRow(), 1).toString());
        insuranceID.setText(cancelInsuranceTable.getValueAt(cancelInsuranceTable.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_cancelInsuranceTableMouseClicked

    private void planComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planComboBoxActionPerformed

    private void submitClaimTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitClaimTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_submitClaimTableMouseClicked

    private void submitClaimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitClaimButtonActionPerformed
        // TODO add your handling code here:
        try {
             JFrame jFrame = new JFrame();
            String select = Constants.GETINSURANCEFORPET + animalLookup.get(animalDropDown.getSelectedItem().toString());
        flag = true;
        flag1 = true;
        flag = ValidationService.validateEmail(contactEmail.getText());
        flag1 = ValidationService.validateNumber(contactNumber.getText());
        if (!flag) {
            JOptionPane.showMessageDialog(jFrame, "Email entered is wrong, please enter correct email!");
        } else if (!flag1) {
            JOptionPane.showMessageDialog(jFrame, "Phone number entered is wrong, please enter correct email!");
        }else{
            ResultSet rs = DatabaseConnection.getData(select, false);

            while (rs.next()) {
                boolean activeInsuranceExists = true;
                Date crrTime = new Date();

                InsuranceClaim claim = new InsuranceClaim(
                        animalLookup.get(animalDropDown.getSelectedItem().toString()),
                        1, WorkFlowStatus.PENDING, Integer.valueOf(claimAmount.getText()), 
                        hospitalLookup.get(hospitalName.getSelectedItem().toString()), 
                        doctorName.getSelectedItem().toString(), contactEmail.getText(), 
                        contactNumber.getText(), crrTime
                );
                
                claim.setInsuranceDetailsId(rs.getInt("id"));
                DatabaseConnection.submitClaim(claim);
                JOptionPane.showMessageDialog(jFrame, "Claim Submitted!");
            }
        }
        } catch (SQLException e) {
            Logger.getLogger(PetOwner.class.getName()).log(Level.SEVERE, null, e);

        }


    }//GEN-LAST:event_submitClaimButtonActionPerformed

    private void contactNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactNumberKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if (!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_contactNumberKeyTyped

    private void insuranceIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insuranceIDKeyTyped
        // TODO add your handling code here:
        char TestChar = evt.getKeyChar();
        if (!(Character.isDigit(TestChar)))
            evt.consume();
    }//GEN-LAST:event_insuranceIDKeyTyped

    private void submitclaimButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        parentPanel.removeAll();
        parentPanel.add(submitClaimPanel);
        parentPanel.repaint();
        parentPanel.revalidate();
        populateTable();
        populateDoctorsInDropDown();
        populateHospitalsInDropDown();
        populateAnimalsForSubmitClaim();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PetOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PetOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PetOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PetOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PetOwner().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JComboBox<String> animalDropDown;
    private javax.swing.JTextField animalIDTextField1;
    private javax.swing.JTextField animalName;
    private javax.swing.JTextField anmlIDCancelTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField breedTextField;
    private javax.swing.JButton cancelInsuranceButton;
    private javax.swing.JPanel cancelInsurancePanel;
    private javax.swing.JButton cancelInsurancePanelButton;
    private javax.swing.JTable cancelInsuranceTable;
    private javax.swing.JTextField claimAmount;
    private javax.swing.JTextField contactEmail;
    private javax.swing.JTextField contactNumber;
    private javax.swing.JComboBox<String> doctorName;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JComboBox<String> existingMedicalConditions;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JComboBox<String> hospitalName;
    private javax.swing.JTextField insuranceID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JComboBox<String> planComboBox;
    private javax.swing.JButton purchaseButton;
    private javax.swing.JButton purchaseInsuranceButton2;
    private javax.swing.JPanel purchaseInsurancePanel;
    private javax.swing.JTable purchaseInsuranceTable;
    private javax.swing.JButton registerAnimalButton;
    private javax.swing.JPanel registerAnimalPanel;
    private javax.swing.JButton registerButton;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JButton submitClaimButton;
    private javax.swing.JPanel submitClaimPanel;
    private javax.swing.JTable submitClaimTable;
    private javax.swing.JButton submitclaimButton;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
    private void populateInsurancePlans() {
        String[] plans = new String[15];

        try {
            plan = DatabaseConnection.getData("Select * from InsurancePlan", false);
            int i = 0;
            while (plan.next()) {
                plans[i] = plan.getString("planName");
                planLookup.put(plan.getString("planName"), plan.getInt("id"));
                i++;
            }
            plans = Arrays.stream(plans).filter(value -> value != null && value.length() > 0).toArray(size -> new String[size]);

        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }

        planComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(plans));
    }

    private void populateAnimalstable() {
        DefaultTableModel model = (DefaultTableModel) purchaseInsuranceTable.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = null;
            String selectStatmt = Constants.GETALLANIMALFOROWNER + ua.getPersonID();
            System.out.print(selectStatmt);
            rs = DatabaseConnection.getData(selectStatmt, false);
            while (rs.next()) {
                Object[] row = {rs.getString("name"), rs.getString("animalType"), rs.getString("breed"), rs.getString("gender")};
                model.addRow(row);
                AnimalDetails animalnew = new AnimalDetails(rs.getString("name"), rs.getString("animalType"),
                        rs.getString("breed"),
                        rs.getInt("age"),
                        rs.getString("gender"),
                        ua.getPersonID(),
                        rs.getString("bloodType")
                );
                animalnew.setId(rs.getInt("id"));
                animals.add(animalnew);
            }

        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);

        }

    }

    private void populateCancelInsuranceTable() {
        DefaultTableModel model = (DefaultTableModel) cancelInsuranceTable.getModel();
        model.setRowCount(0);

        try {
            ResultSet rs = null;
            String selectStatmt = "select * from InsuranceDetails id JOIN AnimalDetails ad ON id.animalId = ad.id WHERE status='ACTIVE' and ad.animalOwnerID = " + ua.getPersonID();
            rs = DatabaseConnection.getData(selectStatmt, false);
            while (rs.next()) {
                Object[] row = {rs.getString("name"), rs.getString("animalType"), rs.getString("breed"), rs.getString("gender")};
                model.addRow(row);
            }

        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private void populateDoctorsInDropDown() {
        String[] doctors = new String[15];

        try {
            ResultSet docs = DatabaseConnection.getData(Constants.GETALLDOCTORS, false);
            int i = 0;
            while (docs.next()) {
                String docName = docs.getString("fname") + " " + docs.getString("lname");
                doctors[i] = docName;
                doctorLookup.put(docName, docs.getInt("id"));
                i++;
            }

            doctors = Arrays.stream(doctors).filter(value -> value != null && value.length() > 0).toArray(size -> new String[size]);

        } catch (SQLException e) {
            Logger.getLogger(DatabaseConnection.class.getName()).log(Level.SEVERE, null, e);
        }

        doctorName.setModel(new javax.swing.DefaultComboBoxModel<>(doctors));
    }

    private void populateHospitalsInDropDown() {
        String[] hospitals = new String[15];

        try {
            ResultSet hospitalN = DatabaseConnection.getData(Constants.GETALLHOSPITALS, false);

            int i = 0;
            while (hospitalN.next()) {
                hospitals[i] = hospitalN.getString("hospitalName");
                hospitalLookup.put(hospitalN.getString("hospitalName"), hospitalN.getInt("id"));
                i++;
            }
            hospitals = Arrays.stream(hospitals).filter(value -> value != null && value.length() > 0).toArray(size -> new String[size]);

        } catch (SQLException e) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, e);
        }
        hospitalName.setModel(new javax.swing.DefaultComboBoxModel<>(hospitals));
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) submitClaimTable.getModel();
        model.setRowCount(0);
        try {
            ResultSet rs = DatabaseConnection.getData(Constants.GETINSURANCEDETAILSFORCLAIM, false);
            while (rs.next()) {
                Object[] row = {rs.getInt("AnimalID"), rs.getString("AnimalName"), rs.getInt("InsuranceID"), rs.getInt("planCoverage"), "ACTIVE"};
                model.addRow(row);
            }

        } catch (SQLException e) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, e);

        }
    }

    private void populateAnimalsForSubmitClaim() {

        String[] animals = new String[15];

        try {
            ResultSet animalnames = DatabaseConnection.getData(Constants.GETALLANIMALFOROWNER + ua.getPersonID(), false);

            int i = 0;
            while (animalnames.next()) {
                animals[i] = animalnames.getString("name");
                animalLookup.put(animalnames.getString("name"), animalnames.getInt("id"));
                i++;
            }
            animals = Arrays.stream(animals).filter(value -> value != null && value.length() > 0).toArray(size -> new String[size]);

        } catch (SQLException e) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, e);
        }
        animalDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(animals));
    }

}
